name: g_mcp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_unity_widget: ^2022.1.1+3
  #auto_size_text: 3.0.0
  cached_network_image: 3.1.0+1
  font_awesome_flutter: 10.1.0
  #google_fonts: 2.2.0
  intl: 0.17.0
  json_path: 0.3.1
  #json_annotation: ^4.3.0
  page_transition: 2.0.4
  #shared_preferences: 2.0.11
  #smooth_page_indicator: 1.0.0+2
  timeago: 3.1.0
  url_launcher: 6.0.15
  path_provider: 2.0.11
  transformer_page_view: 0.1.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  pointer_interceptor: ^0.9.3+2
  firebase_core: ^1.20.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_launcher_icons: 0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/Heading_pro/
    - assets/fonts/QuattrocentoSans/
    - assets/images/
    - jsonfile/
  fonts:
    - family: QuattrocentroSans
      fonts:
        - asset: assets/fonts/QuattrocentoSans/QuattrocentoSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/QuattrocentoSans/QuattrocentoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/QuattrocentoSans/QuattrocentoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/QuattrocentoSans/QuattrocentoSans-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Headingpro
      fonts:
        - asset: assets/fonts/Heading_pro/Heading-Pro-Thin-trial.ttf
          weight: 100
        - asset: assets/fonts/Heading_pro/Heading-Pro-Thin-Italic-trial.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Heading_pro/Heading-Pro-ExtraLight-trial.ttf
          weight: 200
        - asset: assets/fonts/Heading_pro/Heading-Pro-ExtraLight-Italic-trial.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Heading_pro/Heading-Pro-Light-trial.ttf
          weight: 300
        - asset: assets/fonts/Heading_pro/Heading-Pro-Light-Italic-trial.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Heading_pro/Heading-Pro-Italic-trial.ttf
          weight: 500
          style: italic    
        - asset: assets/fonts/Heading_pro/Heading-Pro-Book-trial.ttf
          weight: 600
        - asset: assets/fonts/Heading_pro/Heading-Pro-Book-Italic-trial.ttf
          weight: 600
          style: italic       
        - asset: assets/fonts/Heading_pro/Heading-Pro-Bold-trial.ttf
          weight: 700
        - asset: assets/fonts/Heading_pro/Heading-Pro-Bold-Italic-trial.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Heading_pro/Heading-Pro-ExtraBold-trial.ttf
          weight: 800
        - asset: assets/fonts/Heading_pro/Heading-Pro-ExtraBold-Italic-trial.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Heading_pro/Heading-Pro-Heavy-trial.ttf
          weight: 900
        - asset: assets/fonts/Heading_pro/Heading-Pro-Heavy-Italic-trial.ttf
          weight: 900
          style: italic