// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZTTb-CLKcVyLtr31SBgfTk8BJ2hB5iRs',
    appId: '1:689761636028:web:1f779a01b26a5bd8fd4ab9',
    messagingSenderId: '689761636028',
    projectId: 'gabrielricoestudio-48ad9',
    authDomain: 'gabrielricoestudio-48ad9.firebaseapp.com',
    storageBucket: 'gabrielricoestudio-48ad9.appspot.com',
    measurementId: 'G-PKQYRBQ5PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChJNnuisfFbVN2bx-sq5MhcwhPyaVRaxQ',
    appId: '1:689761636028:android:ab58eba21b64319ffd4ab9',
    messagingSenderId: '689761636028',
    projectId: 'gabrielricoestudio-48ad9',
    storageBucket: 'gabrielricoestudio-48ad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOZu2QrW216mVPrr8Dzbhk-fH6j_XUO0w',
    appId: '1:689761636028:ios:3fd124f1dea5920ffd4ab9',
    messagingSenderId: '689761636028',
    projectId: 'gabrielricoestudio-48ad9',
    storageBucket: 'gabrielricoestudio-48ad9.appspot.com',
    iosClientId: '689761636028-ejb41f9d475722nt2ncj2q8ragd81tud.apps.googleusercontent.com',
    iosBundleId: 'com.GM.GabrielRico',
  );
}
